### ISSUE TITLE
What is the proper way to check if a PDF is password protected?

### ISSUE THREAD

**Issue by rbresjer** [uxmstudio/UXMPDFKit#35]
Previously, I used this piece of code to open a document and ask a password if the PDF appears to be password protected:
```
func openDocument() {
  do {
    document = try PDFDocument(filePath: pdfFilePath, password: password)
  } catch let err {
    switch err as? CGPDFDocumentError {
    case .some(.passwordRequired):
      askPassword(firstTime: true)
    case .some(.couldNotUnlock):
      askPassword(firstTime: false)
    default:
      break
    }
    return
  }
  
  DispatchQueue.main.async {
    self.document?.currentPage = self.page
    self.openViewer()
  }
}
```

However, this doesn't work anymore as the exception thrown in `CGPDFDocument.swift` isn't forwarded. Right now I have implemented this workaround just below the `catch` above, but if feels dirty:
```
  if document?.documentRef == nil {
    askPassword(firstTime: true)
    return
  }
```

What would be the proper way to check if a PDF is password-protected?

Thanks,
Rutger

**Comment by pushchris** [comment]
You would be correct to assume the error should be propagating through. It looks like when we added in the ability to open a PDF from `Data` instead of just a file path this functionality broke. We moved all of the logic to a computed property so that calling it each time would pull from the latest variables that had been set. However, computed properties do not allow for throwing errors, so that is where the holdup is. A solution will be to move that logic to a function. However we will then have to either make the `password`, `filePath` and `fileData` variables read-only or will have to have the `documentRef` recompute when they are changed. Due to my schedule this change will be a couple of days, for the time being checking for `nil` is the best option, unfortunately that won't tell you if it was any of the other errors however. Sorry for the inconvenience!

**Comment by rbresjer** [comment]
Hi @pushchris, thanks for responding! I'll use the nil-check for now, and update as soon as an update is available.

**Comment by rbresjer** [comment]
#8

**Comment by pushchris** [comment]
@rbresjer sorry for the delay, I have pushed code that moves opening of a PDF context to its own method. Would you mind pulling from the master branch and letting me know if it resolves the issue for you? If so I'll go ahead and publish a new version. Thanks

**Comment by rbresjer** [comment]
@pushchris Hi Chris, thanks, I just tested and it works!
