### ISSUE TITLE
Zoom on double tap

### ISSUE THREAD

**Issue by aco314** [uxmstudio/UXMPDFKit#45]
Thanks for taking your time to make this. I have a question i would like to ask.

I am using the single page collectionview to display a PDF, and i can zoom in on the content with pinching. Is it possible to zoom in with simply doubletapping on the collectionview?

If not, is it possible to add this function manually? Im new to programming and i've been trying to google this, without results.

Thanks in advance!

**Comment by pushchris** [comment]
There unfortunately is not a super easy way of doing this at this time. I'll describe in theory what you would need to do:

Essentially, a ```PDFPageContentView``` has methods for zooming ```zoomIncrement``` and ```zoomDecrement```, but in order to access the ```PDFPageContentView``` you will need to access the cell on display inside of the ```PDFSinglePageViewer```. Once you have a reference to the cell, you could just add a ```UITapGestureRecognizer``` to the collection view (make sure to allow touches to propagate through to subviews) that listens for a double tap, then execute the zoom methods inside of the cell on display. 

Hope this helps.

**Comment by aco314** [comment]
I have been trying to do this in the past days, but with no luck as im still a beginner in programming.
I'm sorry for bugging you, but could you please tell me more precise what to do? Or more specifically, how to access the cell?
Once again, sorry. - aco314
