### ISSUE TITLE
Question about highlight

### ISSUE THREAD

**Issue by slehyder** [uxmstudio/UXMPDFKit#50]
"Add PDF level highlighting (instead of using a pen tool, select and highlight PDF text) ".

Is this distant to an early implementation? Is that it seems extremely important to be able to generate annotations more personalized I have been working on your pod and I find it difficult to continue without this I have taken a look at your code but I am not so expert yet, in the language.

**Comment by pushchris** [comment]
The annotation system on whole is currently being reworked to allow for greater flexibility and performing document level writing of the annotations. This is the main priority currently. Enabling highlighting my selecting text is further down the road because it involves parsing the text elements as well to be able to gather their location on the page. What is the use case you are trying to accomplish?
