### ISSUE TITLE
PDFDocument object conflicts with PDFKit.PDFDocument

### ISSUE THREAD

**Issue by amosavian** [uxmstudio/UXMPDFKit#71]
When I embed UXMPDFKit into my project, even without importing the framework in a particulat file, `PDFDocument` object inside library cause Xcode fails to import new `PDFKit.PDFDocument` and mark it as unavailable. I suggest renaming it to `UXMPDFDocument` to avoid ambiguity.

## Your Environment
* iOS Version: 11.0
* Xcode Version: 9.0
* Swift Version: 4.0

**Comment by pushchris** [comment]
@amosavian due to the introduction of PDFKit on iOS there is going to need to be a full re-write of the code to both not conflict, remove redundant code and support features previously not implemented. That is something that is going to take quite a bit of time. I went ahead and namespaced the files in the swift-4.0 branch for the time being however.

**Comment by amosavian** [comment]
Thanks a lot ❤️
